package br.com.bsitecnologia.dashboard.model;

// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Alerta generated by hbm2java
 */
@Entity
@Table(name = "Alerta", catalog = "dashboard")
public class Alerta implements java.io.Serializable {

	private static final long serialVersionUID = -42646393538951083L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status")
	private Status status;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transicaoStatus")
	private TransicaoStatus transicaoStatus;
	
	@Column(name = "minutosDuracaoStatus")
	private Integer minutosDuracaoStatus;
	
	@Column(name = "minutosAntesDataPrevisaoConclusao")
	private Integer minutosAntesDataPrevisaoConclusao;
	
	@Column(name = "minutosAntesDataFim")
	private Integer minutosAntesDataFim;
	
	@Column(name = "corProjetoDashboard")
	private Integer corProjetoDashboard;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alerta")
	private List<EmailTemplate> emailTemplates = new ArrayList<EmailTemplate>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alerta")
	private List<AlertaProjeto> alertaProjetos = new ArrayList<AlertaProjeto>(0);

	public Alerta() {
	}

	public Alerta(Status status, TransicaoStatus transicaoStatus,
			Integer minutosDuracaoStatus,
			Integer minutosAntesDataPrevisaoConclusao,
			Integer minutosAntesDataFim, Integer corProjetoDashboard,
			List<EmailTemplate> emailTemplates, List<AlertaProjeto> alertaProjetos) {
		this.status = status;
		this.transicaoStatus = transicaoStatus;
		this.minutosDuracaoStatus = minutosDuracaoStatus;
		this.minutosAntesDataPrevisaoConclusao = minutosAntesDataPrevisaoConclusao;
		this.minutosAntesDataFim = minutosAntesDataFim;
		this.corProjetoDashboard = corProjetoDashboard;
		this.emailTemplates = emailTemplates;
		this.alertaProjetos = alertaProjetos;
	}

	public Integer getId() {
		return this.id;
	}

	public void ListId(Integer id) {
		this.id = id;
	}

	public Status getStatus() {
		return this.status;
	}

	public void ListStatus(Status status) {
		this.status = status;
	}

	public TransicaoStatus getTransicaoStatus() {
		return this.transicaoStatus;
	}

	public void ListTransicaoStatus(TransicaoStatus transicaoStatus) {
		this.transicaoStatus = transicaoStatus;
	}

	
	public Integer getMinutosDuracaoStatus() {
		return this.minutosDuracaoStatus;
	}

	public void ListMinutosDuracaoStatus(Integer minutosDuracaoStatus) {
		this.minutosDuracaoStatus = minutosDuracaoStatus;
	}

	public Integer getMinutosAntesDataPrevisaoConclusao() {
		return this.minutosAntesDataPrevisaoConclusao;
	}

	public void ListMinutosAntesDataPrevisaoConclusao(
			Integer minutosAntesDataPrevisaoConclusao) {
		this.minutosAntesDataPrevisaoConclusao = minutosAntesDataPrevisaoConclusao;
	}

	public Integer getMinutosAntesDataFim() {
		return this.minutosAntesDataFim;
	}

	public void ListMinutosAntesDataFim(Integer minutosAntesDataFim) {
		this.minutosAntesDataFim = minutosAntesDataFim;
	}

	public Integer getCorProjetoDashboard() {
		return this.corProjetoDashboard;
	}

	public void ListCorProjetoDashboard(Integer corProjetoDashboard) {
		this.corProjetoDashboard = corProjetoDashboard;
	}

	public List<EmailTemplate> getEmailTemplates() {
		return this.emailTemplates;
	}

	public void ListEmailTemplates(List<EmailTemplate> emailTemplates) {
		this.emailTemplates = emailTemplates;
	}

	public List<AlertaProjeto> getAlertaProjetos() {
		return this.alertaProjetos;
	}

	public void ListAlertaProjetos(List<AlertaProjeto> alertaProjetos) {
		this.alertaProjetos = alertaProjetos;
	}

}
