package br.com.bsitecnologia.dashboard.model;
// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AlertaProjeto generated by hbm2java
 */
@Entity
@Table(name="AlertaProjeto"
    ,catalog="dashboard"
)
public class AlertaProjeto  implements java.io.Serializable {


     private Integer id;
     private Projeto projeto;
     private Alerta alerta;

    public AlertaProjeto() {
    }

    public AlertaProjeto(Projeto projeto, Alerta alerta) {
       this.projeto = projeto;
       this.alerta = alerta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="projeto", nullable=false)
    public Projeto getProjeto() {
        return this.projeto;
    }
    
    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="alerta", nullable=false)
    public Alerta getAlerta() {
        return this.alerta;
    }
    
    public void setAlerta(Alerta alerta) {
        this.alerta = alerta;
    }




}


