package br.com.bsitecnologia.dashboard.model;
// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Artefato generated by hbm2java
 */
@Entity
@Table(name="Artefato"
    ,catalog="dashboard"
)
public class Artefato  implements java.io.Serializable {


     private Integer id;
     private ColaboradorProjeto colaboradorProjetoByColaboradorAtualizacao;
     private Projeto projeto;
     private ColaboradorProjeto colaboradorProjetoByColaboradorCriacao;
     private String nome;
     private String path;
     private Date dataCriacao;
     private Date dataAlteracao;

    public Artefato() {
    }

	
    public Artefato(ColaboradorProjeto colaboradorProjetoByColaboradorAtualizacao, Projeto projeto, ColaboradorProjeto colaboradorProjetoByColaboradorCriacao) {
        this.colaboradorProjetoByColaboradorAtualizacao = colaboradorProjetoByColaboradorAtualizacao;
        this.projeto = projeto;
        this.colaboradorProjetoByColaboradorCriacao = colaboradorProjetoByColaboradorCriacao;
    }
    public Artefato(ColaboradorProjeto colaboradorProjetoByColaboradorAtualizacao, Projeto projeto, ColaboradorProjeto colaboradorProjetoByColaboradorCriacao, String nome, String path, Date dataCriacao, Date dataAlteracao) {
       this.colaboradorProjetoByColaboradorAtualizacao = colaboradorProjetoByColaboradorAtualizacao;
       this.projeto = projeto;
       this.colaboradorProjetoByColaboradorCriacao = colaboradorProjetoByColaboradorCriacao;
       this.nome = nome;
       this.path = path;
       this.dataCriacao = dataCriacao;
       this.dataAlteracao = dataAlteracao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="colaboradorAtualizacao", nullable=false)
    public ColaboradorProjeto getColaboradorProjetoByColaboradorAtualizacao() {
        return this.colaboradorProjetoByColaboradorAtualizacao;
    }
    
    public void setColaboradorProjetoByColaboradorAtualizacao(ColaboradorProjeto colaboradorProjetoByColaboradorAtualizacao) {
        this.colaboradorProjetoByColaboradorAtualizacao = colaboradorProjetoByColaboradorAtualizacao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="projeto", nullable=false)
    public Projeto getProjeto() {
        return this.projeto;
    }
    
    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="colaboradorCriacao", nullable=false)
    public ColaboradorProjeto getColaboradorProjetoByColaboradorCriacao() {
        return this.colaboradorProjetoByColaboradorCriacao;
    }
    
    public void setColaboradorProjetoByColaboradorCriacao(ColaboradorProjeto colaboradorProjetoByColaboradorCriacao) {
        this.colaboradorProjetoByColaboradorCriacao = colaboradorProjetoByColaboradorCriacao;
    }

    
    @Column(name="nome", length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="path")
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataCriacao", length=19)
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataAlteracao", length=19)
    public Date getDataAlteracao() {
        return this.dataAlteracao;
    }
    
    public void setDataAlteracao(Date dataAlteracao) {
        this.dataAlteracao = dataAlteracao;
    }




}


