package br.com.bsitecnologia.dashboard.model;

// Generated 01/09/2012 15:14:43 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Artefato generated by hbm2java
 */
@Entity
@Table(name = "Artefato", catalog = "dashboard")
public class Artefato implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaboradorAtualizacao", nullable = false)
	private ColaboradorProjeto colaboradorAtualizacao;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projeto", nullable = false)
	private Projeto projeto;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaboradorCriacao", nullable = false)
	private ColaboradorProjeto colaboradorCriacao;
	
	@Column(name = "nome", length = 100)
	private String nome;
	
	@Column(name = "path")
	private String path;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCriacao", length = 19)
	private Date dataCriacao;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataAlteracao", length = 19)
	private Date dataAlteracao;

	public Artefato() {
	}

	public Artefato(
			ColaboradorProjeto colaboradorAtualizacao,
			Projeto projeto,
			ColaboradorProjeto colaboradorCriacao) {
		this.colaboradorAtualizacao = colaboradorAtualizacao;
		this.projeto = projeto;
		this.colaboradorCriacao = colaboradorCriacao;
	}

	public Artefato(
			ColaboradorProjeto colaboradorAtualizacao,
			Projeto projeto,
			ColaboradorProjeto colaboradorCriacao,
			String nome, String path, Date dataCriacao, Date dataAlteracao) {
		this.colaboradorAtualizacao = colaboradorAtualizacao;
		this.projeto = projeto;
		this.colaboradorCriacao = colaboradorCriacao;
		this.nome = nome;
		this.path = path;
		this.dataCriacao = dataCriacao;
		this.dataAlteracao = dataAlteracao;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ColaboradorProjeto getColaboradorAtualizacao() {
		return this.colaboradorAtualizacao;
	}

	public void setColaboradorAtualizacao(ColaboradorProjeto colaboradorAtualizacao) {
		this.colaboradorAtualizacao = colaboradorAtualizacao;
	}

	public Projeto getProjeto() {
		return this.projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}

	public ColaboradorProjeto getColaboradorCriacao() {
		return this.colaboradorCriacao;
	}

	public void setColaboradorCriacao(
			ColaboradorProjeto colaboradorCriacao) {
		this.colaboradorCriacao = colaboradorCriacao;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Date getDataCriacao() {
		return this.dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

}
