package br.com.bsitecnologia.dashboard.model;
// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AtorExternoTransicaoStatus generated by hbm2java
 */
@Entity
@Table(name="AtorExternoTransicaoStatus"
    ,catalog="dashboard"
)
public class AtorExternoTransicaoStatus  implements java.io.Serializable {


     private Integer id;
     private AtorExterno atorExterno;
     private Projeto projeto;
     private TransicaoStatus transicaoStatus;
     private Set<HistoricoProjeto> historicoProjetos = new HashSet<HistoricoProjeto>(0);

    public AtorExternoTransicaoStatus() {
    }

	
    public AtorExternoTransicaoStatus(AtorExterno atorExterno, Projeto projeto, TransicaoStatus transicaoStatus) {
        this.atorExterno = atorExterno;
        this.projeto = projeto;
        this.transicaoStatus = transicaoStatus;
    }
    public AtorExternoTransicaoStatus(AtorExterno atorExterno, Projeto projeto, TransicaoStatus transicaoStatus, Set<HistoricoProjeto> historicoProjetos) {
       this.atorExterno = atorExterno;
       this.projeto = projeto;
       this.transicaoStatus = transicaoStatus;
       this.historicoProjetos = historicoProjetos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="atorExterno", nullable=false)
    public AtorExterno getAtorExterno() {
        return this.atorExterno;
    }
    
    public void setAtorExterno(AtorExterno atorExterno) {
        this.atorExterno = atorExterno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="projeto", nullable=false)
    public Projeto getProjeto() {
        return this.projeto;
    }
    
    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="transicaoStatus", nullable=false)
    public TransicaoStatus getTransicaoStatus() {
        return this.transicaoStatus;
    }
    
    public void setTransicaoStatus(TransicaoStatus transicaoStatus) {
        this.transicaoStatus = transicaoStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="atorExternoTransicaoStatus")
    public Set<HistoricoProjeto> getHistoricoProjetos() {
        return this.historicoProjetos;
    }
    
    public void setHistoricoProjetos(Set<HistoricoProjeto> historicoProjetos) {
        this.historicoProjetos = historicoProjetos;
    }




}


