package br.com.bsitecnologia.dashboard.model;
// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AtorExterno generated by hbm2java
 */
@Entity
@Table(name="AtorExterno"
    ,catalog="dashboard"
)
public class AtorExterno  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String email;
     private String telefone;
     private String cargo;
     private String empresa;
     private Set<Impedimento> impedimentos = new HashSet<Impedimento>(0);
     private Set<AtorExternoTransicaoStatus> atorExternoTransicaoStatuses = new HashSet<AtorExternoTransicaoStatus>(0);

    public AtorExterno() {
    }

    public AtorExterno(String nome, String email, String telefone, String cargo, String empresa, Set<Impedimento> impedimentos, Set<AtorExternoTransicaoStatus> atorExternoTransicaoStatuses) {
       this.nome = nome;
       this.email = email;
       this.telefone = telefone;
       this.cargo = cargo;
       this.empresa = empresa;
       this.impedimentos = impedimentos;
       this.atorExternoTransicaoStatuses = atorExternoTransicaoStatuses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nome", length=127)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="email", length=127)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="telefone", length=11)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="cargo", length=45)
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    
    @Column(name="empresa", length=45)
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="atorExterno")
    public Set<Impedimento> getImpedimentos() {
        return this.impedimentos;
    }
    
    public void setImpedimentos(Set<Impedimento> impedimentos) {
        this.impedimentos = impedimentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="atorExterno")
    public Set<AtorExternoTransicaoStatus> getAtorExternoTransicaoStatuses() {
        return this.atorExternoTransicaoStatuses;
    }
    
    public void setAtorExternoTransicaoStatuses(Set<AtorExternoTransicaoStatus> atorExternoTransicaoStatuses) {
        this.atorExternoTransicaoStatuses = atorExternoTransicaoStatuses;
    }




}


