package br.com.bsitecnologia.dashboard.model;

// Generated 01/09/2012 15:14:43 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name = "Cargo", catalog = "dashboard", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class Cargo implements java.io.Serializable {

	private static final long serialVersionUID = -2079581154129221126L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "nome", unique = true, length = 45)
	private String nome;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	private List<Colaborador> colaboradores = new ArrayList<Colaborador>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	private List<EmailTemplateColaboradores> emailTemplateColaboradoreses = new ArrayList<EmailTemplateColaboradores>(0);

	public Cargo() {
	}

	public Cargo(String nome, List<Colaborador> colaboradores,
			List<EmailTemplateColaboradores> emailTemplateColaboradoreses) {
		this.nome = nome;
		this.colaboradores = colaboradores;
		this.emailTemplateColaboradoreses = emailTemplateColaboradoreses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public List<Colaborador> getColaboradores() {
		return this.colaboradores;
	}

	public void setColaboradores(List<Colaborador> colaboradors) {
		this.colaboradores = colaboradors;
	}

	public List<EmailTemplateColaboradores> getEmailTemplateColaboradoreses() {
		return this.emailTemplateColaboradoreses;
	}

	public void setEmailTemplateColaboradoreses(List<EmailTemplateColaboradores> emailTemplateColaboradoreses) {
		this.emailTemplateColaboradoreses = emailTemplateColaboradoreses;
	}

}
