package br.com.bsitecnologia.dashboard.model;
// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name="Cargo"
    ,catalog="dashboard"
    , uniqueConstraints = @UniqueConstraint(columnNames="nome") 
)
public class Cargo  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set<Colaborador> colaboradors = new HashSet<Colaborador>(0);
     private Set<EmailTemplateColaboradores> emailTemplateColaboradoreses = new HashSet<EmailTemplateColaboradores>(0);

    public Cargo() {
    }

    public Cargo(String nome, Set<Colaborador> colaboradors, Set<EmailTemplateColaboradores> emailTemplateColaboradoreses) {
       this.nome = nome;
       this.colaboradors = colaboradors;
       this.emailTemplateColaboradoreses = emailTemplateColaboradoreses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nome", unique=true, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cargo")
    public Set<Colaborador> getColaboradors() {
        return this.colaboradors;
    }
    
    public void setColaboradors(Set<Colaborador> colaboradors) {
        this.colaboradors = colaboradors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cargo")
    public Set<EmailTemplateColaboradores> getEmailTemplateColaboradoreses() {
        return this.emailTemplateColaboradoreses;
    }
    
    public void setEmailTemplateColaboradoreses(Set<EmailTemplateColaboradores> emailTemplateColaboradoreses) {
        this.emailTemplateColaboradoreses = emailTemplateColaboradoreses;
    }




}


