package br.com.bsitecnologia.dashboard.model;
// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name="Comentario"
    ,catalog="dashboard"
)
public class Comentario  implements java.io.Serializable {


     private Integer id;
     private Projeto projeto;
     private Colaborador colaborador;
     private String texto;
     private Date data;
     private Set<Impedimento> impedimentos = new HashSet<Impedimento>(0);

    public Comentario() {
    }

	
    public Comentario(Projeto projeto, Colaborador colaborador) {
        this.projeto = projeto;
        this.colaborador = colaborador;
    }
    public Comentario(Projeto projeto, Colaborador colaborador, String texto, Date data, Set<Impedimento> impedimentos) {
       this.projeto = projeto;
       this.colaborador = colaborador;
       this.texto = texto;
       this.data = data;
       this.impedimentos = impedimentos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="projeto", nullable=false)
    public Projeto getProjeto() {
        return this.projeto;
    }
    
    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="colaborador", nullable=false)
    public Colaborador getColaborador() {
        return this.colaborador;
    }
    
    public void setColaborador(Colaborador colaborador) {
        this.colaborador = colaborador;
    }

    
    @Column(name="texto", length=2000)
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data", length=19)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comentario")
    public Set<Impedimento> getImpedimentos() {
        return this.impedimentos;
    }
    
    public void setImpedimentos(Set<Impedimento> impedimentos) {
        this.impedimentos = impedimentos;
    }




}


