package br.com.bsitecnologia.dashboard.model;

// Generated 01/09/2012 15:14:43 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name = "Comentario", catalog = "dashboard")
public class Comentario implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projeto", nullable = false)
	private Projeto projeto;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaborador", nullable = false)
	private Colaborador colaborador;

	@Column(name = "texto", length = 2000)
	private String texto;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data", length = 19)
	private Date data;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	private List<Impedimento> impedimentos = new ArrayList<Impedimento>(0);

	public Comentario() {
	}

	public Comentario(Projeto projeto, Colaborador colaborador) {
		this.projeto = projeto;
		this.colaborador = colaborador;
	}

	public Comentario(Projeto projeto, Colaborador colaborador, String texto,
			Date data, List<Impedimento> impedimentos) {
		this.projeto = projeto;
		this.colaborador = colaborador;
		this.texto = texto;
		this.data = data;
		this.impedimentos = impedimentos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Projeto getProjeto() {
		return this.projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}

	public Colaborador getColaborador() {
		return this.colaborador;
	}

	public void setColaborador(Colaborador colaborador) {
		this.colaborador = colaborador;
	}

	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public List<Impedimento> getImpedimentos() {
		return this.impedimentos;
	}

	public void setImpedimentos(List<Impedimento> impedimentos) {
		this.impedimentos = impedimentos;
	}

}
