package br.com.bsitecnologia.dashboard.model;
// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmailTemplate generated by hbm2java
 */
@Entity
@Table(name="EmailTemplate"
    ,catalog="dashboard"
)
public class EmailTemplate  implements java.io.Serializable {


     private Integer id;
     private Alerta alerta;
     private String conteudoEmail;
     private String tituloEmail;
     private Set<EmailTemplateColaboradores> emailTemplateColaboradoreses = new HashSet<EmailTemplateColaboradores>(0);

    public EmailTemplate() {
    }

	
    public EmailTemplate(Alerta alerta, String conteudoEmail, String tituloEmail) {
        this.alerta = alerta;
        this.conteudoEmail = conteudoEmail;
        this.tituloEmail = tituloEmail;
    }
    public EmailTemplate(Alerta alerta, String conteudoEmail, String tituloEmail, Set<EmailTemplateColaboradores> emailTemplateColaboradoreses) {
       this.alerta = alerta;
       this.conteudoEmail = conteudoEmail;
       this.tituloEmail = tituloEmail;
       this.emailTemplateColaboradoreses = emailTemplateColaboradoreses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="alerta", nullable=false)
    public Alerta getAlerta() {
        return this.alerta;
    }
    
    public void setAlerta(Alerta alerta) {
        this.alerta = alerta;
    }

    
    @Column(name="conteudoEmail", nullable=false, length=2000)
    public String getConteudoEmail() {
        return this.conteudoEmail;
    }
    
    public void setConteudoEmail(String conteudoEmail) {
        this.conteudoEmail = conteudoEmail;
    }

    
    @Column(name="tituloEmail", nullable=false, length=50)
    public String getTituloEmail() {
        return this.tituloEmail;
    }
    
    public void setTituloEmail(String tituloEmail) {
        this.tituloEmail = tituloEmail;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="emailTemplate")
    public Set<EmailTemplateColaboradores> getEmailTemplateColaboradoreses() {
        return this.emailTemplateColaboradoreses;
    }
    
    public void setEmailTemplateColaboradoreses(Set<EmailTemplateColaboradores> emailTemplateColaboradoreses) {
        this.emailTemplateColaboradoreses = emailTemplateColaboradoreses;
    }




}


