package br.com.bsitecnologia.dashboard.model;

// Generated 01/09/2012 15:14:43 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmailTemplate generated by hbm2java
 */
@Entity
@Table(name = "EmailTemplate", catalog = "dashboard")
public class EmailTemplate implements java.io.Serializable {

	private static final long serialVersionUID = -2933634350323057971L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alerta", nullable = false)
	private Alerta alerta;
	
	@Column(name = "conteudoEmail", nullable = false, length = 2000)
	private String conteudoEmail;
	
	@Column(name = "tituloEmail", nullable = false, length = 50)
	private String tituloEmail;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emailTemplate")
	private List<EmailTemplateColaboradores> emailTemplateColaboradoreses = new ArrayList<EmailTemplateColaboradores>(0);

	public EmailTemplate() {
	}

	public EmailTemplate(Alerta alerta, String conteudoEmail, String tituloEmail) {
		this.alerta = alerta;
		this.conteudoEmail = conteudoEmail;
		this.tituloEmail = tituloEmail;
	}

	public EmailTemplate(Alerta alerta, String conteudoEmail,
			String tituloEmail,
			List<EmailTemplateColaboradores> emailTemplateColaboradoreses) {
		this.alerta = alerta;
		this.conteudoEmail = conteudoEmail;
		this.tituloEmail = tituloEmail;
		this.emailTemplateColaboradoreses = emailTemplateColaboradoreses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Alerta getAlerta() {
		return this.alerta;
	}

	public void setAlerta(Alerta alerta) {
		this.alerta = alerta;
	}

	public String getConteudoEmail() {
		return this.conteudoEmail;
	}

	public void setConteudoEmail(String conteudoEmail) {
		this.conteudoEmail = conteudoEmail;
	}

	public String getTituloEmail() {
		return this.tituloEmail;
	}

	public void setTituloEmail(String tituloEmail) {
		this.tituloEmail = tituloEmail;
	}

	public List<EmailTemplateColaboradores> getEmailTemplateColaboradoreses() {
		return this.emailTemplateColaboradoreses;
	}

	public void setEmailTemplateColaboradoreses(List<EmailTemplateColaboradores> emailTemplateColaboradoreses) {
		this.emailTemplateColaboradoreses = emailTemplateColaboradoreses;
	}

}
