package br.com.bsitecnologia.dashboard.model;
// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmailTemplateColaboradores generated by hbm2java
 */
@Entity
@Table(name="EmailTemplateColaboradores"
    ,catalog="dashboard"
)
public class EmailTemplateColaboradores  implements java.io.Serializable {


     private Integer id;
     private Equipe equipe;
     private Cargo cargo;
     private EmailTemplate emailTemplate;
     private Colaborador colaborador;

    public EmailTemplateColaboradores() {
    }

	
    public EmailTemplateColaboradores(EmailTemplate emailTemplate) {
        this.emailTemplate = emailTemplate;
    }
    public EmailTemplateColaboradores(Equipe equipe, Cargo cargo, EmailTemplate emailTemplate, Colaborador colaborador) {
       this.equipe = equipe;
       this.cargo = cargo;
       this.emailTemplate = emailTemplate;
       this.colaborador = colaborador;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="equipe")
    public Equipe getEquipe() {
        return this.equipe;
    }
    
    public void setEquipe(Equipe equipe) {
        this.equipe = equipe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cargo")
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emailTemplate", nullable=false)
    public EmailTemplate getEmailTemplate() {
        return this.emailTemplate;
    }
    
    public void setEmailTemplate(EmailTemplate emailTemplate) {
        this.emailTemplate = emailTemplate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="colaborador")
    public Colaborador getColaborador() {
        return this.colaborador;
    }
    
    public void setColaborador(Colaborador colaborador) {
        this.colaborador = colaborador;
    }




}


