package br.com.bsitecnologia.dashboard.model;
// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Equipe generated by hbm2java
 */
@Entity
@Table(name="Equipe"
    ,catalog="dashboard"
    , uniqueConstraints = @UniqueConstraint(columnNames="nome") 
)
public class Equipe  implements java.io.Serializable {


     private Integer id;
     private Equipe equipe;
     private String nome;
     private Set<Equipe> equipes = new HashSet<Equipe>(0);
     private Set<EmailTemplateColaboradores> emailTemplateColaboradoreses = new HashSet<EmailTemplateColaboradores>(0);
     private Set<EquipeProjeto> equipeProjetos = new HashSet<EquipeProjeto>(0);
     private Set<Colaborador> colaboradors = new HashSet<Colaborador>(0);

    public Equipe() {
    }

	
    public Equipe(String nome) {
        this.nome = nome;
    }
    public Equipe(Equipe equipe, String nome, Set<Equipe> equipes, Set<EmailTemplateColaboradores> emailTemplateColaboradoreses, Set<EquipeProjeto> equipeProjetos, Set<Colaborador> colaboradors) {
       this.equipe = equipe;
       this.nome = nome;
       this.equipes = equipes;
       this.emailTemplateColaboradoreses = emailTemplateColaboradoreses;
       this.equipeProjetos = equipeProjetos;
       this.colaboradors = colaboradors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="equipePai")
    public Equipe getEquipe() {
        return this.equipe;
    }
    
    public void setEquipe(Equipe equipe) {
        this.equipe = equipe;
    }

    
    @Column(name="nome", unique=true, nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="equipe")
    public Set<Equipe> getEquipes() {
        return this.equipes;
    }
    
    public void setEquipes(Set<Equipe> equipes) {
        this.equipes = equipes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="equipe")
    public Set<EmailTemplateColaboradores> getEmailTemplateColaboradoreses() {
        return this.emailTemplateColaboradoreses;
    }
    
    public void setEmailTemplateColaboradoreses(Set<EmailTemplateColaboradores> emailTemplateColaboradoreses) {
        this.emailTemplateColaboradoreses = emailTemplateColaboradoreses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="equipe")
    public Set<EquipeProjeto> getEquipeProjetos() {
        return this.equipeProjetos;
    }
    
    public void setEquipeProjetos(Set<EquipeProjeto> equipeProjetos) {
        this.equipeProjetos = equipeProjetos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="equipe")
    public Set<Colaborador> getColaboradors() {
        return this.colaboradors;
    }
    
    public void setColaboradors(Set<Colaborador> colaboradors) {
        this.colaboradors = colaboradors;
    }




}


