package br.com.bsitecnologia.dashboard.model;

// Generated 01/09/2012 15:14:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Equipe generated by hbm2java
 */
@Entity
@Table(name = "Equipe", catalog = "dashboard", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class Equipe implements java.io.Serializable {

	private static final long serialVersionUID = 6490219298510109730L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipePai")
	private Equipe equipe;
	
	@Column(name = "nome", unique = true, nullable = false, length = 45)
	private String nome;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	private Set<Equipe> equipes = new HashSet<Equipe>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	private Set<EmailTemplateColaboradores> emailTemplateColaboradores = new HashSet<EmailTemplateColaboradores>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	private Set<EquipeProjeto> equipeProjetos = new HashSet<EquipeProjeto>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	private Set<Colaborador> colaboradores = new HashSet<Colaborador>(0);

	public Equipe() {
	}

	public Equipe(String nome) {
		this.nome = nome;
	}

	public Equipe(Equipe equipe, String nome, Set<Equipe> equipes,
			Set<EmailTemplateColaboradores> emailTemplateColaboradores,
			Set<EquipeProjeto> equipeProjetos, Set<Colaborador> colaboradores) {
		this.equipe = equipe;
		this.nome = nome;
		this.equipes = equipes;
		this.emailTemplateColaboradores = emailTemplateColaboradores;
		this.equipeProjetos = equipeProjetos;
		this.colaboradores = colaboradores;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Equipe> getEquipes() {
		return this.equipes;
	}

	public void setEquipes(Set<Equipe> equipes) {
		this.equipes = equipes;
	}

	public Set<EmailTemplateColaboradores> getEmailTemplateColaboradoreses() {
		return this.emailTemplateColaboradores;
	}

	public void setEmailTemplateColaboradoreses(
			Set<EmailTemplateColaboradores> emailTemplateColaboradoreses) {
		this.emailTemplateColaboradores = emailTemplateColaboradoreses;
	}

	public Set<EquipeProjeto> getEquipeProjetos() {
		return this.equipeProjetos;
	}

	public void setEquipeProjetos(Set<EquipeProjeto> equipeProjetos) {
		this.equipeProjetos = equipeProjetos;
	}

	public Set<Colaborador> getColaboradores() {
		return this.colaboradores;
	}

	public void setColaboradores(Set<Colaborador> colaboradores) {
		this.colaboradores = colaboradores;
	}

}
