package br.com.bsitecnologia.dashboard.model;

// Generated 24/09/2012 20:18:49 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * Funcionalidade generated by hbm2java
 */
@Entity
@Table(name = "Funcionalidade", catalog = "dashboard")
public class Funcionalidade implements Serializable, BaseEntity {

	private static final long serialVersionUID = -5171000617685230080L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "nome", length = 45)
	private String nome;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcionalidade")
	private List<AutorizacaoColaborador> autorizacaoColaboradors = new ArrayList<AutorizacaoColaborador>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcionalidade")
	private List<AutorizacaoAtorExterno> autorizacaoAtorExternos = new ArrayList<AutorizacaoAtorExterno>(0);

	public Funcionalidade() {
	}

	public Funcionalidade(String nome,
			List<AutorizacaoColaborador> autorizacaoColaboradors,
			List<AutorizacaoAtorExterno> autorizacaoAtorExternos) {
		this.nome = nome;
		this.autorizacaoColaboradors = autorizacaoColaboradors;
		this.autorizacaoAtorExternos = autorizacaoAtorExternos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public List<AutorizacaoColaborador> getAutorizacaoColaboradors() {
		return this.autorizacaoColaboradors;
	}

	public void setAutorizacaoColaboradors(List<AutorizacaoColaborador> autorizacaoColaboradors) {
		this.autorizacaoColaboradors = autorizacaoColaboradors;
	}

	public List<AutorizacaoAtorExterno> getAutorizacaoAtorExternos() {
		return this.autorizacaoAtorExternos;
	}

	public void setAutorizacaoAtorExternos(List<AutorizacaoAtorExterno> autorizacaoAtorExternos) {
		this.autorizacaoAtorExternos = autorizacaoAtorExternos;
	}

	@Override
	public String getEntityDescription() {
		return nome;
	}

}
