package br.com.bsitecnologia.dashboard.model;

// Generated 01/09/2012 15:14:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Impedimento generated by hbm2java
 */
@Entity
@Table(name = "Impedimento", catalog = "dashboard")
public class Impedimento implements java.io.Serializable {

	private static final long serialVersionUID = 1356611879944932216L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaboradorAutor", nullable = false)
	private Colaborador colaboradorAutor;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "atorExterno")
	private AtorExterno atorExterno;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projeto", nullable = false)
	private Projeto projeto;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaboradorImpedimento")
	private Colaborador colaboradorRelacionadoImpedimento;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comentario", nullable = false)
	private Comentario comentario;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataInicio", nullable = false, length = 19)
	private Date dataInicio;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataFim", length = 19)
	private Date dataFim;

	public Impedimento() {
	}

	public Impedimento(Colaborador colaboradorAutor,
			Projeto projeto, Comentario comentario, Date dataInicio) {
		this.colaboradorAutor = colaboradorAutor;
		this.projeto = projeto;
		this.comentario = comentario;
		this.dataInicio = dataInicio;
	}

	public Impedimento(Colaborador colaboradorAutor,
			AtorExterno atorExterno, Projeto projeto,
			Colaborador colaboradorRelacionadoImpedimento,
			Comentario comentario, Date dataInicio, Date dataFim) {
		this.colaboradorAutor = colaboradorAutor;
		this.atorExterno = atorExterno;
		this.projeto = projeto;
		this.colaboradorRelacionadoImpedimento = colaboradorRelacionadoImpedimento;
		this.comentario = comentario;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Colaborador getColaboradorAutor() {
		return this.colaboradorAutor;
	}

	public void setColaboradorAutor(
			Colaborador colaboradorAutor) {
		this.colaboradorAutor = colaboradorAutor;
	}

	public AtorExterno getAtorExterno() {
		return this.atorExterno;
	}

	public void setAtorExterno(AtorExterno atorExterno) {
		this.atorExterno = atorExterno;
	}

	public Projeto getProjeto() {
		return this.projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}

	public Colaborador getColaboradorRelacionadoImpedimento() {
		return this.colaboradorRelacionadoImpedimento;
	}

	public void setColaboradorRelacionadoImpedimento(
			Colaborador colaboradorRelacionadoImpedimento) {
		this.colaboradorRelacionadoImpedimento = colaboradorRelacionadoImpedimento;
	}

	public Comentario getComentario() {
		return this.comentario;
	}

	public void setComentario(Comentario comentario) {
		this.comentario = comentario;
	}

	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

}
