package br.com.bsitecnologia.dashboard.model;
// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Impedimento generated by hbm2java
 */
@Entity
@Table(name="Impedimento"
    ,catalog="dashboard"
)
public class Impedimento  implements java.io.Serializable {


     private Integer id;
     private Colaborador colaboradorByColaboradorAutor;
     private AtorExterno atorExterno;
     private Projeto projeto;
     private Colaborador colaboradorByColaboradorImpedimento;
     private Comentario comentario;
     private Date dataCriacao;
     private Date dataFinalizacao;

    public Impedimento() {
    }

	
    public Impedimento(Colaborador colaboradorByColaboradorAutor, Projeto projeto, Comentario comentario, Date dataCriacao) {
        this.colaboradorByColaboradorAutor = colaboradorByColaboradorAutor;
        this.projeto = projeto;
        this.comentario = comentario;
        this.dataCriacao = dataCriacao;
    }
    public Impedimento(Colaborador colaboradorByColaboradorAutor, AtorExterno atorExterno, Projeto projeto, Colaborador colaboradorByColaboradorImpedimento, Comentario comentario, Date dataCriacao, Date dataFinalizacao) {
       this.colaboradorByColaboradorAutor = colaboradorByColaboradorAutor;
       this.atorExterno = atorExterno;
       this.projeto = projeto;
       this.colaboradorByColaboradorImpedimento = colaboradorByColaboradorImpedimento;
       this.comentario = comentario;
       this.dataCriacao = dataCriacao;
       this.dataFinalizacao = dataFinalizacao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="colaboradorAutor", nullable=false)
    public Colaborador getColaboradorByColaboradorAutor() {
        return this.colaboradorByColaboradorAutor;
    }
    
    public void setColaboradorByColaboradorAutor(Colaborador colaboradorByColaboradorAutor) {
        this.colaboradorByColaboradorAutor = colaboradorByColaboradorAutor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="atorExterno")
    public AtorExterno getAtorExterno() {
        return this.atorExterno;
    }
    
    public void setAtorExterno(AtorExterno atorExterno) {
        this.atorExterno = atorExterno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="projeto", nullable=false)
    public Projeto getProjeto() {
        return this.projeto;
    }
    
    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="colaboradorImpedimento")
    public Colaborador getColaboradorByColaboradorImpedimento() {
        return this.colaboradorByColaboradorImpedimento;
    }
    
    public void setColaboradorByColaboradorImpedimento(Colaborador colaboradorByColaboradorImpedimento) {
        this.colaboradorByColaboradorImpedimento = colaboradorByColaboradorImpedimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="comentario", nullable=false)
    public Comentario getComentario() {
        return this.comentario;
    }
    
    public void setComentario(Comentario comentario) {
        this.comentario = comentario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataCriacao", nullable=false, length=19)
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataFinalizacao", length=19)
    public Date getDataFinalizacao() {
        return this.dataFinalizacao;
    }
    
    public void setDataFinalizacao(Date dataFinalizacao) {
        this.dataFinalizacao = dataFinalizacao;
    }




}


