package br.com.bsitecnologia.dashboard.model;
// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name="Status"
    ,catalog="dashboard"
    , uniqueConstraints = @UniqueConstraint(columnNames="nome") 
)
public class Status  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set<Alerta> alertas = new HashSet<Alerta>(0);
     private Set<TransicaoStatus> transicaoStatusesForStatusTo = new HashSet<TransicaoStatus>(0);
     private Set<Projeto> projetos = new HashSet<Projeto>(0);
     private Set<TransicaoStatus> transicaoStatusesForStatusFrom = new HashSet<TransicaoStatus>(0);

    public Status() {
    }

	
    public Status(String nome) {
        this.nome = nome;
    }
    public Status(String nome, Set<Alerta> alertas, Set<TransicaoStatus> transicaoStatusesForStatusTo, Set<Projeto> projetos, Set<TransicaoStatus> transicaoStatusesForStatusFrom) {
       this.nome = nome;
       this.alertas = alertas;
       this.transicaoStatusesForStatusTo = transicaoStatusesForStatusTo;
       this.projetos = projetos;
       this.transicaoStatusesForStatusFrom = transicaoStatusesForStatusFrom;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nome", unique=true, nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<Alerta> getAlertas() {
        return this.alertas;
    }
    
    public void setAlertas(Set<Alerta> alertas) {
        this.alertas = alertas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="statusByStatusTo")
    public Set<TransicaoStatus> getTransicaoStatusesForStatusTo() {
        return this.transicaoStatusesForStatusTo;
    }
    
    public void setTransicaoStatusesForStatusTo(Set<TransicaoStatus> transicaoStatusesForStatusTo) {
        this.transicaoStatusesForStatusTo = transicaoStatusesForStatusTo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<Projeto> getProjetos() {
        return this.projetos;
    }
    
    public void setProjetos(Set<Projeto> projetos) {
        this.projetos = projetos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="statusByStatusFrom")
    public Set<TransicaoStatus> getTransicaoStatusesForStatusFrom() {
        return this.transicaoStatusesForStatusFrom;
    }
    
    public void setTransicaoStatusesForStatusFrom(Set<TransicaoStatus> transicaoStatusesForStatusFrom) {
        this.transicaoStatusesForStatusFrom = transicaoStatusesForStatusFrom;
    }




}


