package br.com.bsitecnologia.dashboard.model;
// Generated 01/09/2012 11:28:22 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TransicaoStatus generated by hbm2java
 */
@Entity
@Table(name="TransicaoStatus"
    ,catalog="dashboard"
    , uniqueConstraints = @UniqueConstraint(columnNames="nome") 
)
public class TransicaoStatus  implements java.io.Serializable {


     private Integer id;
     private Status statusByStatusTo;
     private Status statusByStatusFrom;
     private String nome;
     private Set<AtorExternoTransicaoStatus> atorExternoTransicaoStatuses = new HashSet<AtorExternoTransicaoStatus>(0);
     private Set<Alerta> alertas = new HashSet<Alerta>(0);
     private Set<HistoricoProjeto> historicoProjetos = new HashSet<HistoricoProjeto>(0);

    public TransicaoStatus() {
    }

	
    public TransicaoStatus(Status statusByStatusTo, Status statusByStatusFrom) {
        this.statusByStatusTo = statusByStatusTo;
        this.statusByStatusFrom = statusByStatusFrom;
    }
    public TransicaoStatus(Status statusByStatusTo, Status statusByStatusFrom, String nome, Set<AtorExternoTransicaoStatus> atorExternoTransicaoStatuses, Set<Alerta> alertas, Set<HistoricoProjeto> historicoProjetos) {
       this.statusByStatusTo = statusByStatusTo;
       this.statusByStatusFrom = statusByStatusFrom;
       this.nome = nome;
       this.atorExternoTransicaoStatuses = atorExternoTransicaoStatuses;
       this.alertas = alertas;
       this.historicoProjetos = historicoProjetos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="statusTo", nullable=false)
    public Status getStatusByStatusTo() {
        return this.statusByStatusTo;
    }
    
    public void setStatusByStatusTo(Status statusByStatusTo) {
        this.statusByStatusTo = statusByStatusTo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="statusFrom", nullable=false)
    public Status getStatusByStatusFrom() {
        return this.statusByStatusFrom;
    }
    
    public void setStatusByStatusFrom(Status statusByStatusFrom) {
        this.statusByStatusFrom = statusByStatusFrom;
    }

    
    @Column(name="nome", unique=true, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transicaoStatus")
    public Set<AtorExternoTransicaoStatus> getAtorExternoTransicaoStatuses() {
        return this.atorExternoTransicaoStatuses;
    }
    
    public void setAtorExternoTransicaoStatuses(Set<AtorExternoTransicaoStatus> atorExternoTransicaoStatuses) {
        this.atorExternoTransicaoStatuses = atorExternoTransicaoStatuses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transicaoStatus")
    public Set<Alerta> getAlertas() {
        return this.alertas;
    }
    
    public void setAlertas(Set<Alerta> alertas) {
        this.alertas = alertas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transicaoStatus")
    public Set<HistoricoProjeto> getHistoricoProjetos() {
        return this.historicoProjetos;
    }
    
    public void setHistoricoProjetos(Set<HistoricoProjeto> historicoProjetos) {
        this.historicoProjetos = historicoProjetos;
    }




}


