package br.com.bsitecnologia.dashboard.model;

// Generated 01/09/2012 15:14:43 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TransicaoStatus generated by hbm2java
 */
@Entity
@Table(name = "TransicaoStatus", catalog = "dashboard", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class TransicaoStatus implements java.io.Serializable {

	private static final long serialVersionUID = -8348462824515978851L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "statusTo", nullable = false)
	private Status statusByStatusTo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "statusFrom", nullable = false)
	private Status statusByStatusFrom;
	
	@Column(name = "nome", unique = true, length = 45)
	private String nome;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transicaoStatus")
	private Set<AtorExternoTransicaoStatus> atorExternoTransicaoStatuses = new HashSet<AtorExternoTransicaoStatus>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transicaoStatus")
	private Set<Alerta> alertas = new HashSet<Alerta>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transicaoStatus")
	private Set<HistoricoProjeto> historicoProjetos = new HashSet<HistoricoProjeto>(0);

	public TransicaoStatus() {
	}

	public TransicaoStatus(Status statusByStatusTo, Status statusByStatusFrom) {
		this.statusByStatusTo = statusByStatusTo;
		this.statusByStatusFrom = statusByStatusFrom;
	}

	public TransicaoStatus(Status statusByStatusTo, Status statusByStatusFrom,
			String nome,
			Set<AtorExternoTransicaoStatus> atorExternoTransicaoStatuses,
			Set<Alerta> alertas, Set<HistoricoProjeto> historicoProjetos) {
		this.statusByStatusTo = statusByStatusTo;
		this.statusByStatusFrom = statusByStatusFrom;
		this.nome = nome;
		this.atorExternoTransicaoStatuses = atorExternoTransicaoStatuses;
		this.alertas = alertas;
		this.historicoProjetos = historicoProjetos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Status getStatusByStatusTo() {
		return this.statusByStatusTo;
	}

	public void setStatusByStatusTo(Status statusByStatusTo) {
		this.statusByStatusTo = statusByStatusTo;
	}

	public Status getStatusByStatusFrom() {
		return this.statusByStatusFrom;
	}

	public void setStatusByStatusFrom(Status statusByStatusFrom) {
		this.statusByStatusFrom = statusByStatusFrom;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<AtorExternoTransicaoStatus> getAtorExternoTransicaoStatuses() {
		return this.atorExternoTransicaoStatuses;
	}

	public void setAtorExternoTransicaoStatuses(Set<AtorExternoTransicaoStatus> atorExternoTransicaoStatuses) {
		this.atorExternoTransicaoStatuses = atorExternoTransicaoStatuses;
	}

	public Set<Alerta> getAlertas() {
		return this.alertas;
	}

	public void setAlertas(Set<Alerta> alertas) {
		this.alertas = alertas;
	}

	public Set<HistoricoProjeto> getHistoricoProjetos() {
		return this.historicoProjetos;
	}

	public void setHistoricoProjetos(Set<HistoricoProjeto> historicoProjetos) {
		this.historicoProjetos = historicoProjetos;
	}

}
