package br.com.bsitecnologia.dashboard.model;

// Generated 24/09/2012 20:18:49 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * UsuarioColaborador generated by hbm2java
 */
@Entity
@Table(name = "UsuarioColaborador", catalog = "dashboard")
public class UsuarioColaborador implements Serializable, BaseEntity {

	private static final long serialVersionUID = 2638528707644798533L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaborador", nullable = false)
	private Colaborador colaborador;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false)
	private Usuario usuario;

	public UsuarioColaborador() {
	}

	public UsuarioColaborador(Colaborador colaborador, Usuario usuario) {
		this.colaborador = colaborador;
		this.usuario = usuario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Colaborador getColaborador() {
		return this.colaborador;
	}

	public void setColaborador(Colaborador colaborador) {
		this.colaborador = colaborador;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Override
	public String getEntityDescription() {
		return String.format("Usuario: %s, Colaborador: %s", usuario.getEntityDescription(), colaborador.getEntityDescription());
	}

}
