package br.com.bsitecnologia.dashboard.model;

// Generated 24/09/2012 20:18:49 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * UsuarioAtorExterno generated by hbm2java
 */
@Entity
@Table(name = "UsuarioAtorExterno", catalog = "dashboard")
public class UsuarioAtorExterno implements Serializable, BaseEntity {

	private static final long serialVersionUID = 5454890261376384608L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "atorExterno", nullable = false)
	private AtorExterno atorExterno;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false)
	private Usuario usuario;

	public UsuarioAtorExterno() {
	}

	public UsuarioAtorExterno(AtorExterno atorExterno, Usuario usuario) {
		this.atorExterno = atorExterno;
		this.usuario = usuario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AtorExterno getAtorExterno() {
		return this.atorExterno;
	}

	public void setAtorExterno(AtorExterno atorExterno) {
		this.atorExterno = atorExterno;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Override
	public String getEntityDescription() {
		return String.format("Usuario: %s, AtorExterno: %s", usuario.getLogin(), atorExterno.getNome());
	}

}
